[package]
name = "pc_tycoon"
version = "0.1.0"
edition = "2021"
default-run = "pc_tycoon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
imgui-glfw-rs = "0.4.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[[bin]]
name = "pc_tycoon"
path = "src/main.rs"

[[bin]]
name = "part_builder"
path = "src/bin/part_builder/mod.rs"
